### PR TITLE
Make universal UserData, delete duplicate classes

### PR DESCRIPTION
**Pull request by shivamCode0**
The `if using mysql else if using h2 ...` can be removed

### CODE REVIEW

**Comment by NoScapeDev** [comment]
Applied.

**Comment by luni-moon** [comment]
Why the hell did you not just merge this PR? If you really wanted to be the only contributor, then make it private xD.

**Comment by shivamCode0** [comment]
> Why the hell did you not just merge this PR? If you really wanted to be the only contributor, then make it private xD.

I spoke to @NoScapeDev on Discord about the modifications, just chill

**Comment by luni-moon** [comment]
> > Why the hell did you not just merge this PR? If you really wanted to be the only contributor, then make it private xD.
> 
> I spoke to @NoScapeDev on Discord about the modifications, just chill

I am chill, I just thought it was weird without inside info lol. I will be classy and apologise for my words, and getting involved in already discussed material.

**Comment by shivamCode0** [comment]
> > > Why the hell did you not just merge this PR? If you really wanted to be the only contributor, then make it private xD.
> > 
> > 
> > I spoke to @NoScapeDev on Discord about the modifications, just chill
> 
> I am chill, I just thought it was weird without inside info lol. I will be classy and apologise for my words, and getting involved in already discussed material.

That's fair. I guess it could seem like that without looking at the git changes.

**Comment by luni-moon** [comment]
> > > > Why the hell did you not just merge this PR? If you really wanted to be the only contributor, then make it private xD.
> > > 
> > > 
> > > I spoke to @NoScapeDev on Discord about the modifications, just chill
> > 
> > 
> > I am chill, I just thought it was weird without inside info lol. I will be classy and apologise for my words, and getting involved in already discussed material.
> 
> That's fair. I guess it could seem like that without looking at the git changes.

Yeah, I should probably learn to look further next time.

**Pull request closed without merging**
